### ISSUE TITLE
logger is not defined

### ISSUE THREAD

**Issue by dsmatana** [rtr-nettest/rmbtws#8]
It seems something overwrites logger
Was trying example in [test/Websockettest.html](https://github.com/rtr-nettest/rmbtws/blob/5cac4e97c28438da49fb3c3318a499a1b6fbdaa0/test/Websockettest.html)

![image](https://user-images.githubusercontent.com/4609432/28368717-a378765a-6c95-11e7-8e18-f9f997bad373.png)
![image](https://user-images.githubusercontent.com/4609432/28368730-b2a0de9c-6c95-11e7-8f5c-5742cf855549.png)

**Comment by cproof** [comment]
Sorry, I can't reproduce the error. Can you please give a more detailed explaination? Is the issue still present in the latest version?

**Comment by dsmatana** [comment]
Sorry my bad
...in my implementation I renamed `log` to `logger` simply because variable `log` was just undefined after inclusion of `logger.js`. No idea why so I supposed it's a bug.
